### PR TITLE
Make the default styles more sensible defaults and provide style props

### PR DESCRIPTION
**Pull request by invig**

### CODE REVIEW

**Comment by franzejr** [comment]
@invig, Thank you very much! I'd say it was a todo!

What do you think if we pass `wrapperStyle`, `countryStyle`, `textStyle` in the propTypes as not required?

**Comment by invig** [comment]
Yep good idea!

**Comment by franzejr** [comment]
Thanks, @invig ! Do you have more ideas for the plugin?! Are you using it in production or in some app? Just curious. BTW, thank you very much. I'm merging it right now!

**Comment by invig** [comment]
I’m working on an app at the moment that will use it in production soon. I’ll probably make a few contributions just to get it up to what I need it to do (flags are going to be a big win I think) and possibly add a few callbacks around verification to try to make sure numbers are legit.

**Comment by franzejr** [comment]
Awesome, @invig ! Let us know!

**Pull request merged**
